[General]
#################### General ####################

ScreenWidth="1920"
ScreenHeight="1080"
ScreenPadding=""

Font="Noto Sans CJK JP"
FontSize="12"

KeyboardSize="0.4"

RoundCorners="18"

Locale=""
HourFormat="HH:mm"
DateFormat="dddd d"

HeaderText=""

#################### Background ####################

BackgroundPlaceholder=""
Background="Backgrounds/dotfiles.jpg"
BackgroundSpeed=""
PauseBackground=""
DimBackground="0.18"
CropBackground="true"
BackgroundHorizontalAlignment="center"
BackgroundVerticalAlignment="center"

#################### Colors ####################

HeaderTextColor="#f7d4b5"
DateTextColor="#f7d4b5"
TimeTextColor="#ffead2"

FormBackgroundColor="#061a22"
BackgroundColor="#061a22"
DimBackgroundColor="#061a22"

LoginFieldBackgroundColor="#082631"
PasswordFieldBackgroundColor="#082631"
LoginFieldTextColor="#ffead2"
PasswordFieldTextColor="#ffead2"
UserIconColor="#f6a36d"
PasswordIconColor="#f6a36d"

PlaceholderTextColor="#9bb8bd"
WarningColor="#ffb48f"

LoginButtonTextColor="#061a22"
LoginButtonBackgroundColor="#f6a36d"
SystemButtonsIconsColor="#f7d4b5"
SessionButtonTextColor="#f7d4b5"
VirtualKeyboardButtonTextColor="#f7d4b5"

DropdownTextColor="#061a22"
DropdownSelectedBackgroundColor="#f6a36d"
DropdownBackgroundColor="#c98364"

HighlightTextColor="#061a22"
HighlightBackgroundColor="#f6a36d"
HighlightBorderColor="transparent"

HoverUserIconColor="#ffead2"
HoverPasswordIconColor="#ffead2"
HoverSystemButtonsIconsColor="#ffead2"
HoverSessionButtonTextColor="#ffead2"
HoverVirtualKeyboardButtonTextColor="#ffead2"

#################### Form ####################

PartialBlur="true"
FullBlur=""
BlurMax="24"
Blur="2.0"

HaveFormBackground="true"
FormPosition="left"

#################### Virtual Keyboard ####################

VirtualKeyboardPosition="left"

#################### Interface Behavior ####################

HideVirtualKeyboard="false"
HideSystemButtons="false"
HideLoginButton="false"

ForceLastUser="true"
PasswordFocus="true"
HideCompletePassword="true"
AllowEmptyPassword="false"
AllowUppercaseLettersInUsernames="false"
BypassSystemButtonsChecks="false"
RightToLeftLayout="false"

#################### Translation ####################

TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateSessionSelection=""
TranslateVirtualKeyboardButtonOn=""
TranslateVirtualKeyboardButtonOff=""
