[Metadata]
Name=Matugen
Version=1
Author=Matugen
Description=Matugen generated dark Fcitx5 theme
ScaleWithDPI=True

[InputPanel]
NormalColor={{colors.on_surface.default.hex}}
HighlightCandidateColor={{colors.on_primary.default.hex}}
HighlightColor={{colors.on_primary.default.hex}}
HighlightBackgroundColor={{colors.primary.default.hex}}
CandidateLabelColor={{colors.primary.default.hex}}
HighlightCandidateLabelColor={{colors.on_primary.default.hex}}
CandidateCommentColor={{colors.on_surface_variant.default.hex}}
HighlightCandidateCommentColor={{colors.on_primary.default.hex}}
PageButtonAlignment=Last Candidate
UseAllHorizontalSpaceForHighlight=True

[InputPanel/TextMargin]
Left=8
Right=8
Top=6
Bottom=6

[InputPanel/ContentMargin]
Left=6
Right=6
Top=6
Bottom=6

[InputPanel/Background]
Color={{colors.surface.default.hex}}
BorderColor={{colors.primary.default.hex}}
BorderWidth=2

[InputPanel/Background/Margin]
Left=3
Right=3
Top=3
Bottom=3

[InputPanel/Highlight]
Color={{colors.primary.default.hex}}
BorderColor={{colors.primary.default.hex}}
BorderWidth=1

[InputPanel/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[InputPanel/PrevPage]
Image=prev.png

[InputPanel/PrevPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[InputPanel/NextPage]
Image=next.png

[InputPanel/NextPage/ClickMargin]
Left=5
Right=5
Top=4
Bottom=4

[Menu]
NormalColor={{colors.on_surface.default.hex}}
HighlightCandidateColor={{colors.on_primary.default.hex}}

[Menu/Background]
Color={{colors.surface.default.hex}}
BorderColor={{colors.primary.default.hex}}
BorderWidth=2

[Menu/Background/Margin]
Left=3
Right=3
Top=3
Bottom=3

[Menu/ContentMargin]
Left=6
Right=6
Top=6
Bottom=6

[Menu/CheckBox]
Image=radio.png

[Menu/SubMenu]
Image=arrow.png

[Menu/Highlight]
Color={{colors.primary.default.hex}}

[Menu/Highlight/Margin]
Left=5
Right=5
Top=5
Bottom=5

[Menu/Separator]
Color={{colors.outline.default.hex}}

[Menu/TextMargin]
Left=8
Right=8
Top=6
Bottom=6

[AccentColorField]
0=Input Panel Border
1=Input Panel Highlight Candidate Background
2=Input Panel Highlight Candidate Border
3=Input Panel Highlight
4=Menu Border
5=Menu Separator
6=Menu Selected Item Background
