add_newline = true
palette = "tokyo_night_matugen"

format = """
[](fg:surface)\
$os\
[](fg:surface bg:blue)\
$username\
[](fg:blue bg:purple)\
$directory\
[](fg:purple bg:green)\
$git_branch\
$git_status\
[](fg:green bg:surface)\
$cmd_duration\
[](fg:surface)\
$line_break$character"""

[palettes.tokyo_night_matugen]
base = "{{colors.surface.default.hex}}"
surface = "{{colors.surface_container.default.hex}}"
fg = "{{colors.on_surface.default.hex}}"
blue = "{{colors.primary.default.hex}}"
purple = "{{colors.secondary.default.hex}}"
green = "{{colors.tertiary.default.hex}}"
red = "{{colors.error.default.hex}}"
yellow = "{{colors.tertiary_fixed.default.hex}}"

[os]
disabled = false
style = "bg:surface fg:blue"
format = "[$symbol ]($style)"

[username]
show_always = true
style_user = "bg:blue fg:base"
style_root = "bg:red fg:base"
format = "[ $user ]($style)"

[directory]
style = "bg:purple fg:base"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Scripts" = "󰲋 "

[git_branch]
symbol = " "
style = "bg:green fg:base"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:green fg:base"
format = "[$all_status$ahead_behind ]($style)"

[cmd_duration]
min_time = 500
style = "bg:surface fg:yellow"
format = "[ $duration ]($style)"

[character]
success_symbol = "[❯](bold blue)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"

[line_break]
disabled = false
